function out = model
%
% BellowSPABlockForce.m
%
% Model exported on Oct 10 2021, 17:06 by COMSOL 5.6.0.401.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('C:\Users\lajesu3766\OneDrive - Nexus365\Yao\ICRA2022\BellowSPA');

model.label('BellowSPABlockForce2.mph');

model.param.set('L', '66[mm]', 'The "Effective Length" of the bellow SPA');
model.param.set('Rm', '6[mm]', 'The "Average Radius" of the bellow SPA');
model.param.set('N', '6', 'The number of bellow convolutions');
model.param.set('Ri', '2[mm]', 'The "Inner Radius" of the bellow SPA');
model.param.set('t', '1.5[mm]', 'The "WallThickness" of the bellow');
model.param.set('Es', '450[kPa]', 'The "Young''s Modulus" of the soft material');
model.param.set('Pf', '10[kPa]', 'The target final pressure');
model.param.set('P', '0[Pa]', 'The simulation pressure');
model.param.set('Ps', '0.1[kPa]', 'The magitude of the simulation pressure step');
model.param.set('Nu', '0.49', 'The soft material Possion''s Ratio');
model.param.set('miu', '1.16[g/cm^3]', 'The soft material density');
model.param.group.create('par2');
model.param('par2').set('R2', 'L/N/4');
model.param('par2').set('R1', 'R2');
model.param('par2').set('f', 'Rm*2 - Ri*2 - R2 - R1', 'The "Flank" of the bellow');
model.param('par2').set('Ro', 'Rm*2-Ri', 'The "Outer Radius" of the bellow SPA');
model.param('par2').set('A1', '(sqrt((Ro+t)^2-(Rm+t)^2))/(Rm- Ri)');
model.param('par2').set('B1', '-1');
model.param('par2').set('C01', 'A1*(Ri+t)');
model.param('par2').set('C1', 'C01-t*sqrt(A1^2+B1^2)');
model.param('par2').set('A2', '-A1');
model.param('par2').set('B2', '-1');
model.param('par2').set('C02', '-A2*(Ri+t)');
model.param('par2').set('C2', 'C02-t*sqrt(A2^2+B2^2)');
model.param('par2').set('x11', '-(-B1*t+ C1)/A1');
model.param('par2').set('x21', '-(-B2*t+ C2)/A2');
model.param('par2').set('y11', '-t');
model.param('par2').set('y21', '-t');
model.param('par2').set('x12', '-Rm');
model.param('par2').set('x22', 'Rm');
model.param('par2').set('y22', '-(A2*Rm+ C2)/B2');
model.param('par2').set('y12', '-(-A1*Rm+ C1)/B1');
model.param.label('BasicParameter');
model.param('par2').label('ModelProperty');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').label('Geometry');
model.component('comp1').geom('geom1').lengthUnit('mm');
model.component('comp1').geom('geom1').scaleUnitValue(true);
model.component('comp1').geom('geom1').geomRep('comsol');
model.component('comp1').geom('geom1').create('wp1', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp1').label('InnerBellowGeometry');
model.component('comp1').geom('geom1').feature('wp1').set('unite', true);
model.component('comp1').geom('geom1').feature('wp1').geom.create('ca1', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca1').label('LowerArc');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca1').set('center', {'0' 'Ri+ R2'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca1').set('r', 'R2');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca1').set('angle1', -90);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca1').set('angle2', 0);
model.component('comp1').geom('geom1').feature('wp1').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls1').label('flank');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls1').set('coord1', {'R2' 'Ri+R2'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls1').set('coord2', {'R2' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('ca2', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca2').label('UpperArc');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca2').set('center', {'R2+R1' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca2').set('r', 'R1');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca2').set('angle1', 90);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ca2').set('angle2', 180);
model.component('comp1').geom('geom1').feature('wp1').geom.create('ccur1', 'ConvertToCurve');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ccur1').label('HalfBellowConv');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ccur1').selection('input').set({'ca1' 'ca2' 'ls1'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('mir1', 'Mirror');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('mir1').set('keep', true);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('mir1').set('pos', {'R2+R1' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('mir1').selection('input').set({'ccur1'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('ccur2', 'ConvertToCurve');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ccur2').label('BellowConv');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ccur2').selection('input').set({'ccur1' 'mir1'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('arr1', 'Array');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').set('type', 'linear');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').set('selresult', true);
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').set('selresultshow', 'all');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').set('linearsize', 'N');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').set('displ', {'L/N' '0'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('arr1').selection('input').set({'ccur2'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('ls2', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls2').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls2').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls2').set('coord2', {'0' 'Ri'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('ls3', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls3').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls3').set('coord1', {'L' '0'});
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls3').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls3').set('coord2', {'L' 'Ri'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('ls4', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls4').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls4').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('ls4').set('coord2', {'L' '0'});
model.component('comp1').geom('geom1').feature('wp1').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp1').geom.feature('csol1').selection('input').set({'arr1' 'ls2' 'ls3' 'ls4'});
model.component('comp1').geom('geom1').create('rev1', 'Revolve');
model.component('comp1').geom('geom1').feature('rev1').set('angtype', 'full');
model.component('comp1').geom('geom1').feature('rev1').set('origfaces', false);
model.component('comp1').geom('geom1').feature('rev1').set('axis', [1 0]);
model.component('comp1').geom('geom1').feature('rev1').selection('input').set({'wp1'});
model.component('comp1').geom('geom1').create('wp2', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp2').label('InnerBottomLayer');
model.component('comp1').geom('geom1').feature('wp2').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp2').set('unite', true);
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls1').set('coord1', {'x11' 'y11'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls1').set('coord2', {'x21' 'y21'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls2', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls2').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls2').set('coord1', {'x11' 'y11'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls2').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls2').set('coord2', {'x12' 'y12'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls3', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls3').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls3').set('coord1', {'x21' 'y21'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls3').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls3').set('coord2', {'x22' 'y22'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls4', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls4').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls4').set('coord1', {'x12' 'y12'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls4').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls4').set('coord2', {'x12' '-Ro'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls5', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls5').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls5').set('coord1', {'x22' 'y22'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls5').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls5').set('coord2', {'x22' '-Ro'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('ls6', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls6').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls6').set('coord1', {'x12' '-Ro'});
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls6').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('ls6').set('coord2', {'x22' '-Ro'});
model.component('comp1').geom('geom1').feature('wp2').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp2').geom.feature('csol1').selection('input').set({'ls1' 'ls2' 'ls3' 'ls4' 'ls5' 'ls6'});
model.component('comp1').geom('geom1').create('ext1', 'Extrude');
model.component('comp1').geom('geom1').feature('ext1').setIndex('distance', 'L', 0);
model.component('comp1').geom('geom1').feature('ext1').selection('input').set({'wp2'});
model.component('comp1').geom('geom1').create('uni1', 'Union');
model.component('comp1').geom('geom1').feature('uni1').set('intbnd', false);
model.component('comp1').geom('geom1').feature('uni1').selection('input').set({'ext1' 'rev1'});
model.component('comp1').geom('geom1').create('wp3', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp3').label('OuterBellowGeometry');
model.component('comp1').geom('geom1').feature('wp3').set('unite', true);
model.component('comp1').geom('geom1').feature('wp3').geom.create('ca1', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca1').label('LowerArc2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca1').set('center', {'0' 'Ri+ R2'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca1').set('r', 'R2-t');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca1').set('angle1', -90);
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca1').set('angle2', 0);
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls1').label('flank2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls1').set('coord1', {'R2-t' 'Ri+R2'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls1').set('coord2', {'R2-t' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ca2', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca2').label('UpperArc2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca2').set('center', {'R2+R1' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca2').set('r', 'R1+t');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca2').set('angle1', 90);
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ca2').set('angle2', 180);
model.component('comp1').geom('geom1').feature('wp3').geom.create('ccur1', 'ConvertToCurve');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ccur1').label('HalfBellowConv2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ccur1').selection('input').set({'ca1' 'ca2' 'ls1'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('mir1', 'Mirror');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('mir1').set('keep', true);
model.component('comp1').geom('geom1').feature('wp3').geom.feature('mir1').set('pos', {'R2+R1' 'Ri+R2+f'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('mir1').selection('input').set({'ccur1'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ccur2', 'ConvertToCurve');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ccur2').label('BellowConv2');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ccur2').selection('input').set({'ccur1' 'mir1'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('arr1', 'Array');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('arr1').set('type', 'linear');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('arr1').set('linearsize', 'N');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('arr1').set('displ', {'L/N' '0'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('arr1').selection('input').set({'ccur2'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls2', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls2').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls2').set('coord1', {'-t' '0'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls2').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls2').set('coord2', {'-t' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls3', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls3').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls3').set('coord1', {'L+t' '0'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls3').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls3').set('coord2', {'L+t' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls4', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls4').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls4').set('coord1', {'-t' '0'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls4').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls4').set('coord2', {'L+t' '0'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls5', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls5').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls5').set('coord1', {'-t' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls5').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls5').set('coord2', {'0' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('ls6', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls6').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls6').set('coord1', {'L' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls6').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('ls6').set('coord2', {'L+t' 'Ri+t'});
model.component('comp1').geom('geom1').feature('wp3').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp3').geom.feature('csol1').selection('input').set({'arr1' 'ls2' 'ls3' 'ls4' 'ls5' 'ls6'});
model.component('comp1').geom('geom1').create('rev2', 'Revolve');
model.component('comp1').geom('geom1').feature('rev2').set('angtype', 'full');
model.component('comp1').geom('geom1').feature('rev2').set('origfaces', false);
model.component('comp1').geom('geom1').feature('rev2').set('axis', [1 0]);
model.component('comp1').geom('geom1').feature('rev2').selection('input').set({'wp3'});
model.component('comp1').geom('geom1').create('wp4', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp4').label('OuterBottomLayer');
model.component('comp1').geom('geom1').feature('wp4').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp4').set('quickx', '-t');
model.component('comp1').geom('geom1').feature('wp4').set('unite', true);
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls1').set('coord1', {'-Ri-t' '0'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls1').set('coord2', {'-Rm- t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls2', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls2').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls2').set('coord1', {'Ri+t' '0'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls2').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls2').set('coord2', {'Rm+t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls3', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls3').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls3').set('coord1', {'-(Ri+t)' '0'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls3').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls3').set('coord2', {'Ri+t' '0'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls4', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls4').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls4').set('coord1', {'-Rm- t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls4').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls4').set('coord2', {'-Rm- t' '-Ro-t'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls5', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls5').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls5').set('coord1', {'Rm+t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls5').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls5').set('coord2', {'Rm+t' '-Ro-t'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('ls6', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls6').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls6').set('coord1', {'-Rm- t' '-Ro-t'});
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls6').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('ls6').set('coord2', {'Rm+ t' '-Ro-t'});
model.component('comp1').geom('geom1').feature('wp4').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp4').geom.feature('csol1').selection('input').set({'ls1' 'ls2' 'ls3' 'ls4' 'ls5' 'ls6'});
model.component('comp1').geom('geom1').create('ext2', 'Extrude');
model.component('comp1').geom('geom1').feature('ext2').setIndex('distance', 'L+t*2', 0);
model.component('comp1').geom('geom1').feature('ext2').selection('input').set({'wp4'});
model.component('comp1').geom('geom1').create('uni2', 'Union');
model.component('comp1').geom('geom1').feature('uni2').set('intbnd', false);
model.component('comp1').geom('geom1').feature('uni2').selection('input').set({'ext2' 'rev2'});
model.component('comp1').geom('geom1').create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('dif1').selection('input').set({'uni2'});
model.component('comp1').geom('geom1').feature('dif1').selection('input2').set({'uni1'});
model.component('comp1').geom('geom1').create('wp5', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp5').label('AirInlet');
model.component('comp1').geom('geom1').feature('wp5').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp5').set('quickx', '-t');
model.component('comp1').geom('geom1').feature('wp5').set('unite', true);
model.component('comp1').geom('geom1').feature('wp5').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp5').geom.feature('c1').set('r', 'Ri+t');
model.component('comp1').geom('geom1').create('ext3', 'Extrude');
model.component('comp1').geom('geom1').feature('ext3').setIndex('distance', '6', 0);
model.component('comp1').geom('geom1').feature('ext3').set('reverse', true);
model.component('comp1').geom('geom1').feature('ext3').selection('input').set({'wp5'});
model.component('comp1').geom('geom1').create('uni3', 'Union');
model.component('comp1').geom('geom1').feature('uni3').set('intbnd', false);
model.component('comp1').geom('geom1').feature('uni3').selection('input').set({'dif1' 'ext3'});
model.component('comp1').geom('geom1').create('wp6', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp6').label('AirInletChannel');
model.component('comp1').geom('geom1').feature('wp6').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp6').set('quickx', '-t-6');
model.component('comp1').geom('geom1').feature('wp6').set('unite', true);
model.component('comp1').geom('geom1').feature('wp6').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp6').geom.feature('c1').set('r', 1.5);
model.component('comp1').geom('geom1').create('ext4', 'Extrude');
model.component('comp1').geom('geom1').feature('ext4').setIndex('distance', '6+t', 0);
model.component('comp1').geom('geom1').feature('ext4').selection('input').set({'wp6'});
model.component('comp1').geom('geom1').create('dif2', 'Difference');
model.component('comp1').geom('geom1').feature('dif2').selection('input').set({'uni3'});
model.component('comp1').geom('geom1').feature('dif2').selection('input2').set({'ext4'});
model.component('comp1').geom('geom1').create('wp7', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp7').label('InextensibleLayer');
model.component('comp1').geom('geom1').feature('wp7').set('quickz', '-Ro-t');
model.component('comp1').geom('geom1').feature('wp7').set('unite', true);
model.component('comp1').geom('geom1').feature('wp7').geom.create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('wp7').geom.feature('r1').set('pos', {'-t' '-0.5*(t*2 + Rm*2)'});
model.component('comp1').geom('geom1').feature('wp7').geom.feature('r1').set('size', {'L+ t*2' 't*2 + Rm*2'});
model.component('comp1').geom('geom1').create('ext5', 'Extrude');
model.component('comp1').geom('geom1').feature('ext5').setIndex('distance', 't', 0);
model.component('comp1').geom('geom1').feature('ext5').set('reverse', true);
model.component('comp1').geom('geom1').feature('ext5').selection('input').set({'wp7'});
model.component('comp1').geom('geom1').create('uni4', 'Union');
model.component('comp1').geom('geom1').feature('uni4').set('intbnd', false);
model.component('comp1').geom('geom1').feature('uni4').selection('input').set({'dif2' 'ext5'});
model.component('comp1').geom('geom1').create('wp8', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp8').label('FrameConnect');
model.component('comp1').geom('geom1').feature('wp8').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp8').set('quickx', '-t-6');
model.component('comp1').geom('geom1').feature('wp8').set('unite', true);
model.component('comp1').geom('geom1').feature('wp8').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('c1').set('r', 'Ri+t');
model.component('comp1').geom('geom1').feature('wp8').geom.create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('c2').set('pos', {'Rm*2' '-Ro-t+2'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('c2').set('r', 2);
model.component('comp1').geom('geom1').feature('wp8').geom.create('c3', 'Circle');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('c3').set('pos', {'-Rm*2' '-Ro-t+2'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('c3').set('r', 2);
model.component('comp1').geom('geom1').feature('wp8').geom.create('ca1', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca1').set('r', 'Ri+t*2');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca1').set('angle2', 180);
model.component('comp1').geom('geom1').feature('wp8').geom.create('ca2', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca2').set('center', {'Rm*2' '-Ro-t+2'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca2').set('r', '2+t');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca2').set('angle1', -90);
model.component('comp1').geom('geom1').feature('wp8').geom.create('ca3', 'CircularArc');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca3').set('center', {'-Rm*2' '-Ro-t+2'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca3').set('r', '2+t');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca3').set('angle1', 90);
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ca3').set('angle2', 270);
model.component('comp1').geom('geom1').feature('wp8').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls1').set('coord1', {'-Rm*2' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls1').set('coord2', {'Rm*2' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp8').geom.create('ls2', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls2').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls2').set('coord1', {'-Ri-t*2' '0'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls2').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls2').set('coord2', {'-Rm*2' '-Ro+4'});
model.component('comp1').geom('geom1').feature('wp8').geom.create('ls3', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls3').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls3').set('coord1', {'Ri+t*2' '0'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls3').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('ls3').set('coord2', {'Rm*2' '-Ro+4'});
model.component('comp1').geom('geom1').feature('wp8').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('csol1').selection('input').set({'ca1' 'ca2' 'ca3' 'ls1' 'ls2' 'ls3'});
model.component('comp1').geom('geom1').feature('wp8').geom.create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('wp8').geom.feature('dif1').selection('input').set({'csol1'});
model.component('comp1').geom('geom1').feature('wp8').geom.feature('dif1').selection('input2').set({'c1' 'c2' 'c3'});
model.component('comp1').geom('geom1').create('ext6', 'Extrude');
model.component('comp1').geom('geom1').feature('ext6').setIndex('distance', '6', 0);
model.component('comp1').geom('geom1').feature('ext6').selection('input').set({'wp8'});
model.component('comp1').geom('geom1').create('wp9', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp9').label('EndCap');
model.component('comp1').geom('geom1').feature('wp9').set('quickplane', 'yz');
model.component('comp1').geom('geom1').feature('wp9').set('quickx', 'L+t');
model.component('comp1').geom('geom1').feature('wp9').set('unite', true);
model.component('comp1').geom('geom1').feature('wp9').geom.create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('c1').set('r', 'Ri+t');
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls1', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls1').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls1').set('coord1', {'-Ri-t' '0'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls1').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls1').set('coord2', {'-Rm-t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls5', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls5').label('Line Segment 2');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls5').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls5').set('coord1', {'Ri+t' '0'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls5').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls5').set('coord2', {'Rm+t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls6', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls6').label('Line Segment 3');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls6').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls6').set('coord1', {'-Ri-t' '0'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls6').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls6').set('coord2', {'Ri+t' '0'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls7', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls7').label('Line Segment 4');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls7').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls7').set('coord1', {'-Rm-t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls7').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls7').set('coord2', {'-Rm-t' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls8', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls8').label('Line Segment 5');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls8').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls8').set('coord1', {'Rm+t' '-sqrt((Ro+t)^2-(Rm+t)^2)'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls8').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls8').set('coord2', {'Rm+t' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('ls9', 'LineSegment');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls9').label('Line Segment 6');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls9').set('specify1', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls9').set('coord1', {'-Rm-t' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls9').set('specify2', 'coord');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('ls9').set('coord2', {'Rm+t' '-Ro-t*2'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('csol1', 'ConvertToSolid');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('csol1').selection('input').set({'ls1' 'ls5' 'ls6' 'ls7' 'ls8' 'ls9'});
model.component('comp1').geom('geom1').feature('wp9').geom.create('uni1', 'Union');
model.component('comp1').geom('geom1').feature('wp9').geom.feature('uni1').selection('input').set({'c1' 'csol1'});
model.component('comp1').geom('geom1').create('ext7', 'Extrude');
model.component('comp1').geom('geom1').feature('ext7').setIndex('distance', 't', 0);
model.component('comp1').geom('geom1').feature('ext7').selection('input').set({'wp9'});
model.component('comp1').geom('geom1').create('sel1', 'ExplicitSelection');
model.component('comp1').geom('geom1').feature('sel1').label('Fix');
model.component('comp1').geom('geom1').feature('sel1').selection('selection').init(2);
model.component('comp1').geom('geom1').feature('sel1').selection('selection').set('ext6(1)', [1 2 3 4 5 6 7 8 9 14 15 16 17 18 19 20]);
model.component('comp1').geom('geom1').feature('sel1').selection('selection').set('uni4(1)', [1 4 5 7 8]);
model.component('comp1').geom('geom1').feature('sel1').set('groupcontang', true);
model.component('comp1').geom('geom1').create('sel2', 'ExplicitSelection');
model.component('comp1').geom('geom1').feature('sel2').label('Outer');
model.component('comp1').geom('geom1').feature('sel2').selection('selection').init(2);
model.component('comp1').geom('geom1').feature('sel2').selection('selection').set('ext6(1)', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20]);
model.component('comp1').geom('geom1').feature('sel2').selection('selection').set('uni4(1)', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 25 26 37 41 43 44 45 46 47 48 49 50 59 60 63 65 67 68 79 80 81 82 83 84 85 86 87 88 92 94 95 96 97 98 99 100 101 102 111 112 115 117 119 120 131 132 133 134 135 136 137 138 139 140 144 146 147 148 149 150 151 152 153 154 163 164 167 169 171 172 183 184 185 186 187 188 189 190 191 192 196 198 199 200 201 202 203 204 205 206 215 216 219 221 223 224 235 236 237 238 239 240 241 242 243 244 248 250 251 252 253 254 255 256 257 258 267 268 271 273 275 276 287 288 289 290 291 292 293 294 295 296 300 302 303 304 305 306 307 308 309 310 319 320 323 325 327 328 339 340 341 342 343 344 345 346 348 355 356 357 358 359 360 361]);
model.component('comp1').geom('geom1').feature('sel2').selection('selection').set('ext7(1)', [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]);
model.component('comp1').geom('geom1').feature('sel2').set('groupcontang', true);
model.component('comp1').geom('geom1').create('comsel1', 'ComplementSelection');
model.component('comp1').geom('geom1').feature('comsel1').set('entitydim', 2);
model.component('comp1').geom('geom1').feature('comsel1').label('Inner');
model.component('comp1').geom('geom1').feature('comsel1').set('input', {'sel2'});
model.component('comp1').geom('geom1').create('uni5', 'Union');
model.component('comp1').geom('geom1').feature('uni5').selection('input').set({'ext6' 'ext7' 'uni4'});
model.component('comp1').geom('geom1').create('cyl1', 'Cylinder');
model.component('comp1').geom('geom1').feature('cyl1').set('pos', {'L+t*2' '0' '-Ro-2*t-5'});
model.component('comp1').geom('geom1').feature('cyl1').set('r', 'Rm*2.5');
model.component('comp1').geom('geom1').feature('cyl1').set('h', 5);
model.component('comp1').geom('geom1').feature('fin').label('Form Assembly');
model.component('comp1').geom('geom1').feature('fin').set('action', 'assembly');
model.component('comp1').geom('geom1').feature('fin').set('imprint', true);
model.component('comp1').geom('geom1').feature('fin').set('pairtype', 'contact');
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.component('comp1').view('view10').tag('view101');
model.component('comp1').view('view8').tag('view10');
model.component('comp1').view('view9').tag('view11');
model.component('comp1').view('view101').tag('view12');
model.view.create('view8', 2);
model.view.create('view9', 3);

model.component('comp1').pair.create('p1', 'Contact');
model.component('comp1').pair('p1').source.set([395 396 397]);
model.component('comp1').pair('p1').destination.set([311 375 389]);

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('mat2', 'Common');
model.component('comp1').material('mat1').selection.set([2]);
model.component('comp1').material('mat1').propertyGroup.create('Lame', ['Lam' native2unicode(hex2dec({'00' 'e9'}), 'unicode') ' parameters']);
model.component('comp1').material('mat2').selection.set([1 3 4 5 6]);

model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');
model.component('comp1').physics('solid').create('fix3', 'Fixed', 3);
model.component('comp1').physics('solid').feature('fix3').selection.set([1]);
model.component('comp1').physics('solid').create('fix2', 'Fixed', 2);
model.component('comp1').physics('solid').feature('fix2').selection.set([394]);
model.component('comp1').physics('solid').create('bndl1', 'BoundaryLoad', 2);
model.component('comp1').physics('solid').feature('bndl1').selection.named('geom1_comsel1');
model.component('comp1').physics('solid').create('gr1', 'Gravity', 3);
model.component('comp1').physics('solid').feature('gr1').selection.set([1 2 3 4 5]);
model.component('comp1').physics('solid').create('cnt1', 'SolidContact', 2);
model.component('comp1').physics('solid').create('hmm1', 'HyperelasticModel', 3);
model.component('comp1').physics('solid').feature('hmm1').selection.set([2]);

model.component('comp1').view('view1').set('transparency', true);
model.component('comp1').view('view1').set('transparencylevel', 0.30000000000000004);
model.component('comp1').view('view2').axis.set('xmin', -17.753387451171875);
model.component('comp1').view('view2').axis.set('xmax', 89.41525268554688);
model.component('comp1').view('view2').axis.set('ymin', -26.318862915039062);
model.component('comp1').view('view2').axis.set('ymax', 30.854473114013672);
model.component('comp1').view('view3').axis.set('xmin', -45.62800216674805);
model.component('comp1').view('view3').axis.set('xmax', 45.62800216674805);
model.component('comp1').view('view3').axis.set('ymin', -24.342058181762695);
model.component('comp1').view('view3').axis.set('ymax', 24.342058181762695);
model.component('comp1').view('view4').axis.set('xmin', -10.615004539489746);
model.component('comp1').view('view4').axis.set('xmax', 76.61500549316406);
model.component('comp1').view('view4').axis.set('ymin', -22.518144607543945);
model.component('comp1').view('view4').axis.set('ymax', 24.018144607543945);
model.component('comp1').view('view5').axis.set('xmin', -34.50857162475586);
model.component('comp1').view('view5').axis.set('xmax', 34.50857162475586);
model.component('comp1').view('view5').axis.set('ymin', -13.735316276550293);
model.component('comp1').view('view5').axis.set('ymax', 23.08460235595703);
model.component('comp1').view('view6').axis.set('xmin', -21.088571548461914);
model.component('comp1').view('view6').axis.set('xmax', 21.088571548461914);
model.component('comp1').view('view6').axis.set('ymin', -11.250531196594238);
model.component('comp1').view('view6').axis.set('ymax', 11.250531196594238);
model.component('comp1').view('view7').axis.set('xmin', -8.627142906188965);
model.component('comp1').view('view7').axis.set('xmax', 8.627142906188965);
model.component('comp1').view('view7').axis.set('ymin', -4.602489948272705);
model.component('comp1').view('view7').axis.set('ymax', 4.602489948272705);
model.view('view8').axis.set('xmin', -1.9910011291503906);
model.view('view8').axis.set('xmax', 1.9910011291503906);
model.view('view8').axis.set('ymin', -1.009342908859253);
model.view('view8').axis.set('ymax', 1.009342908859253);
model.view('view9').set('transparency', true);
model.component('comp1').view('view10').label('View 10.1');
model.component('comp1').view('view10').axis.set('xmin', -31.404029846191406);
model.component('comp1').view('view10').axis.set('xmax', 91.4040298461914);
model.component('comp1').view('view10').axis.set('ymin', -32.75840377807617);
model.component('comp1').view('view10').axis.set('ymax', 32.75840377807617);
model.component('comp1').view('view11').label('View 11');
model.component('comp1').view('view11').axis.set('xmin', -29.444583892822266);
model.component('comp1').view('view11').axis.set('xmax', 29.444583892822266);
model.component('comp1').view('view11').axis.set('ymin', -16.4583740234375);
model.component('comp1').view('view11').axis.set('ymax', 14.958374977111816);
model.component('comp1').view('view12').label('View 12');
model.component('comp1').view('view12').axis.set('xmin', -29.13925552368164);
model.component('comp1').view('view12').axis.set('xmax', 29.13925552368164);
model.component('comp1').view('view12').axis.set('ymin', -16.29548454284668);
model.component('comp1').view('view12').axis.set('ymax', 14.795486450195312);

model.component('comp1').material('mat1').label('Soft Material');
model.component('comp1').material('mat1').propertyGroup('def').set('youngsmodulus', 'Es');
model.component('comp1').material('mat1').propertyGroup('def').set('poissonsratio', 'Nu');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'miu');
model.component('comp1').material('mat1').propertyGroup('Lame').set('lambLame', '');
model.component('comp1').material('mat1').propertyGroup('Lame').set('muLame', 'Es/(2*(1+0.49))');
model.component('comp1').material('mat2').label('Rigid Material');
model.component('comp1').material('mat2').propertyGroup('def').set('youngsmodulus', '2.5E9');
model.component('comp1').material('mat2').propertyGroup('def').set('poissonsratio', '0.394');
model.component('comp1').material('mat2').propertyGroup('def').set('density', '1175');

model.component('comp1').physics('solid').feature('lemm1').set('MixedFormulation', 'pFormulation');
model.component('comp1').physics('solid').feature('fix3').label('Fixed Constraint 1');
model.component('comp1').physics('solid').feature('bndl1').set('LoadType', 'FollowerPressure');
model.component('comp1').physics('solid').feature('bndl1').set('FollowerPressure', 'P');
model.component('comp1').physics('solid').feature('gr1').set('g', {'g_const'; '0'; '0'});
model.component('comp1').physics('solid').feature('gr1').active(false);
model.component('comp1').physics('solid').feature('cnt1').set('pairs', 'p1');
model.component('comp1').physics('solid').feature('hmm1').set('Compressibility_NeoHookean', 'Incompressible');

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('p1', 'Parametric');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature.remove('fcDef');

model.result.numerical.create('int1', 'IntSurface');
model.result.numerical('int1').selection.set([394]);
model.result.numerical('int1').set('probetag', 'none');
model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg3', 'PlotGroup3D');
model.result('pg1').create('vol1', 'Volume');
model.result('pg1').feature('vol1').set('expr', 'solid.mises');
model.result('pg1').feature('vol1').create('def1', 'Deform');
model.result('pg3').create('vol1', 'Volume');
model.result('pg3').feature('vol1').set('expr', 'solid.evol');
model.result('pg3').feature('vol1').create('def1', 'Deform');

model.study('std1').feature('stat').set('plot', true);
model.study('std1').feature('stat').set('useparam', true);
model.study('std1').feature('stat').set('pname', {'P'});
model.study('std1').feature('stat').set('plistarr', {'range(0, Ps, Pf)'});
model.study('std1').feature('stat').set('punit', {'Pa'});

model.sol('sol1').attach('std1');
model.sol('sol1').feature('st1').label('Compile Equations: Stationary');
model.sol('sol1').feature('v1').label('Dependent Variables 1.1');
model.sol('sol1').feature('v1').set('clistctrl', {'p1'});
model.sol('sol1').feature('v1').set('cname', {'P'});
model.sol('sol1').feature('v1').set('clist', {'range(0, Ps, Pf)'});
model.sol('sol1').feature('v1').feature('comp1_u').set('scalemethod', 'manual');
model.sol('sol1').feature('v1').feature('comp1_u').set('scaleval', '5e-3');
model.sol('sol1').feature('v1').feature('comp1_solid_pw').set('scalemethod', 'manual');
model.sol('sol1').feature('v1').feature('comp1_solid_pw').set('scaleval', 10000000);
model.sol('sol1').feature('s1').label('Stationary Solver 1.1');
model.sol('sol1').feature('s1').set('probesel', 'none');
model.sol('sol1').feature('s1').feature('dDef').label('Direct 2');
model.sol('sol1').feature('s1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('p1').label('Parametric 1.1');
model.sol('sol1').feature('s1').feature('p1').set('pname', {'P'});
model.sol('sol1').feature('s1').feature('p1').set('plistarr', {'range(0, Ps, Pf)'});
model.sol('sol1').feature('s1').feature('p1').set('punit', {'Pa'});
model.sol('sol1').feature('s1').feature('p1').set('porder', 'constant');
model.sol('sol1').feature('s1').feature('p1').set('uselsqdata', false);
model.sol('sol1').feature('s1').feature('p1').set('plot', true);
model.sol('sol1').feature('s1').feature('fc1').label('Fully Coupled 1.1');
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('dtech', 'const');
model.sol('sol1').feature('s1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('s1').feature('d1').label('Suggested Direct Solver (solid)');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d1').set('pivotperturb', 1.0E-9);
model.sol('sol1').feature('s1').feature('d1').set('nliniterrefine', true);
model.sol('sol1').feature('s1').feature('i1').label('Suggested Iterative Solver (solid)');
model.sol('sol1').feature('s1').feature('i1').set('prefuntype', 'right');
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').set('rhob', 40);
model.sol('sol1').feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 2');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').label('SOR 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 2');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').label('SOR 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.8);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').set('thresh', 0.1);
model.sol('sol1').runAll;

model.result.numerical('int1').set('innerinput', 'manual');
model.result.numerical('int1').set('expr', {'solid.RFz'});
model.result.numerical('int1').set('unit', {'N'});
model.result.numerical('int1').set('descr', {'Reaction force, z component'});
model.result.numerical('int1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg1').label('Stress');
model.result('pg1').set('edges', false);
model.result('pg1').feature('vol1').set('unit', 'MPa');
model.result('pg1').feature('vol1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg1').feature('vol1').set('rangecoloractive', true);
model.result('pg1').feature('vol1').set('rangecolormax', 0.5);
model.result('pg1').feature('vol1').set('colortable', 'RainbowLight');
model.result('pg1').feature('vol1').set('resolution', 'normal');
model.result('pg1').feature('vol1').feature('def1').set('scaleactive', true);
model.result('pg3').label('Strain');
model.result('pg3').set('edges', false);
model.result('pg3').feature('vol1').set('const', {'solid.refpntx' '0' 'Reference point for moment computation, x coordinate'; 'solid.refpnty' '0' 'Reference point for moment computation, y coordinate'; 'solid.refpntz' '0' 'Reference point for moment computation, z coordinate'});
model.result('pg3').feature('vol1').set('rangecoloractive', true);
model.result('pg3').feature('vol1').set('rangecolormin', -5.254471739474506E-15);
model.result('pg3').feature('vol1').set('rangecolormax', 0.5);
model.result('pg3').feature('vol1').set('colortable', 'RainbowLight');
model.result('pg3').feature('vol1').set('resolution', 'normal');
model.result('pg3').feature('vol1').feature('def1').set('scaleactive', true);

out = model;
